Models/StudyGroupMember.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ArranStudyGroup.Models
{
	public class StudyGroupMember
	{
        //nromal getters and setters
        [Display(Name = "Student Number")]
        public string StudentNumber { get; set; }
        [Display(Name = "Name")]
        public string FirstName { get; set; }
        [Display(Name = "Surname")]
        public string LastName { get; set; }
        [Display(Name = "Email Address")]
        public string Email { get; set; }
        [Display(Name = "Link To Personal Page")]
        public string myLink { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArranStudyGroup.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/StudyGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArranStudyGroup.Models;


namespace ArranStudyGroup.Controllers
{
    public class StudyGroupController : Controller
    {
        public ActionResult ListOfPeopleIndex()
        {
            var members = new List<StudyGroupMember>
        {
                //some of the following people are real people just not In INF 272
            new StudyGroupMember { StudentNumber = "u23655675", FirstName = "Arran", LastName = "Lamond", Email = "u23655675@tuks.co.za", myLink = "~/HTML/Arran.html"},
            new StudyGroupMember { StudentNumber = "u24641342", FirstName = "Micheal", LastName = "Neto", Email = "u24641342@tuks.co.za", myLink = "~/HTML/Michael.html"},
            new StudyGroupMember { StudentNumber = "u23582724", FirstName = "Vuyo", LastName = "Angura", Email = "u23582724@tuks.co.za", myLink = "~/HTML/Vuyo.html"},
            new StudyGroupMember { StudentNumber = "u23557509", FirstName = "Tanyaradzwa", LastName = "Masara", Email = "u23557509@tuks.co.za", myLink = "~/HTML/Tanyaradzwa.html"},
            new StudyGroupMember { StudentNumber = "u04613628", FirstName = "Andreas", LastName = "Bester", Email = "u04613628@tuks.co.za", myLink = "~/HTML/Andreas.html"}
        };
            //send to view XDD
            ViewBag.Members = members;
            return View(members);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("SAMPLE PAGE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="peopleDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            List of People
                        </a>
                        <div class="dropdown-menu" aria-labelledby="peopleDropdown">
                            <a class="dropdown-item" href="@Url.Action("ListOfPeopleIndex", "StudyGroup")">Complete List Of People</a>
                            <a class="dropdown-item" href="@Url.Content("~/HTML/Arran.html")">Arran Lamond</a>
                            <a class="dropdown-item" href="@Url.Content("~/HTML/Michael.html")">Micheal Neto</a>
                            <a class="dropdown-item" href="@Url.Content("~/HTML/Vuyo.html")">Vuyo Angura</a>
                            <a class="dropdown-item" href="@Url.Content("~/HTML/Tanyaradzwa.html")">Tanyaradzwa Masara</a>
                            <a class="dropdown-item" href="@Url.Content("~/HTML/Andreas.html")">Andreas Bester</a>

                        </div>
                    </li>
                    @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>

Views/StudyGroup/ListOfPeopleIndex.cshtml
@model IEnumerable<ArranStudyGroup.Models.StudyGroupMember>
@{
    ViewBag.Title = "Study Group Members";
}

<h2>Table of People</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.StudentNumber)</th>
            <th>@Html.DisplayNameFor(model => model.FirstName)</th>
            <th>@Html.DisplayNameFor(model => model.LastName)</th>
            <th>@Html.DisplayNameFor(model => model.Email)</th>
            <th>@Html.DisplayNameFor(model => model.myLink)</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var member in Model)
        {
            <tr>
                <td>@member.StudentNumber</td>
                <td>@member.FirstName</td>
                <td>@member.LastName</td>
                <td>@member.Email</td>
                <td> <a href="@Url.Content(member.myLink)" class="btn btn-primary">Click here brah</a> </td>
            </tr>
        }   
    </tbody>
</table>